// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AddMembersForm: typeof import('./src/components/AddMembersForm.vue')['default']
    AddResourcesForm: typeof import('./src/components/AddResourcesForm.vue')['default']
    BarChart: typeof import('./src/components/BarChart.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    GroupMembersExplorer: typeof import('./src/components/GroupMembersExplorer.vue')['default']
    GroupMembersRanking: typeof import('./src/components/GroupMembersRanking.vue')['default']
    LoginForm: typeof import('./src/components/LoginForm.vue')['default']
    Modal: typeof import('./src/components/Modal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SignUpForm: typeof import('./src/components/SignUpForm.vue')['default']
  }
}
